> This notebook downloads the data provided by UNLP Shared Task and combines the data for testing set into one file.

In [2]:
import requests
import pandas as pd

In [28]:
url_train = "https://raw.githubusercontent.com/unlp-workshop/unlp-2025-shared-task/main/data/techniques_classification/train.parquet"
url_test = "https://raw.githubusercontent.com/unlp-workshop/unlp-2025-shared-task/main/data/techniques_classification/test.csv"
url_solution_classif = "https://raw.githubusercontent.com/unlp-workshop/unlp-2025-shared-task/main/data/techniques_classification/solution.csv"
url_solution_span = "https://raw.githubusercontent.com/unlp-workshop/unlp-2025-shared-task/refs/heads/main/data/span_detection/solution.csv"

local_filename_train = "../data/train.parquet"
local_filename_test = "../data/test.csv"
local_filename_solution_classif = "../data/solution_classif.csv"
local_filename_solution_span = "../data/solution_span.csv"

In [29]:
def download_file(url, local_filename):
    response = requests.get(url)
    if response.status_code == 200:
        with open(local_filename, 'wb') as f:
            f.write(response.content)
        print(f"File downloaded successfully as {local_filename}")
    else:
        print(f"Failed to download file. Status code: {response.status_code}")

In [30]:
download_file(url_train, local_filename_train)
download_file(url_test, local_filename_test)
download_file(url_solution_classif, local_filename_solution_classif)
download_file(url_solution_span, local_filename_solution_span)

File downloaded successfully as ../data/train.parquet
File downloaded successfully as ../data/test.csv
File downloaded successfully as ../data/solution_classif.csv
File downloaded successfully as ../data/solution_span.csv

In [31]:
train = pd.read_parquet(local_filename_train)
test = pd.read_csv(local_filename_test)
solution_classif = pd.read_csv(local_filename_solution_classif)
solution_span = pd.read_csv(local_filename_solution_span)

display(train.head())
display(test.head())
display(solution_classif.head())
display(solution_span.head())

,id,content,lang,manipulative,techniques,trigger_words
0,0bb0c7fa-101b-4583-a5f9-9d503339141c,Новий огляд мапи DeepState від російського вій...,uk,True,"[euphoria, loaded_language]","[[27, 63], [65, 88], [90, 183], [186, 308]]"
1,7159f802-6f99-4e9d-97bd-6f565a4a0fae,Недавно 95 квартал жёстко поглумился над русск...,ru,True,"[loaded_language, cherry_picking]","[[0, 40], [123, 137], [180, 251], [253, 274]]"
2,e6a427f1-211f-405f-bd8b-70798458d656,🤩\nТим часом йде евакуація Бєлгородського авто...,uk,True,"[loaded_language, euphoria]","[[55, 100]]"
3,1647a352-4cd3-40f6-bfa1-d87d42e34eea,В Україні найближчим часом мають намір посилит...,uk,False,None,None
4,9c01de00-841f-4b50-9407-104e9ffb03bf,"Расчёты 122-мм САУ 2С1 ""Гвоздика"" 132-й бригад...",ru,True,[loaded_language],"[[114, 144]]"

,id,content
0,521cd2e8-dd9f-42c4-98ba-c0c8890ff1ba,"Они просрали нашу технику, положили кучу людей..."
1,9b2a61e4-d14e-4ff7-b304-e73d720319bf,❗️\nКитай предлагает отдать оккупированные тер...
2,f0f1c236-80a8-4d25-b30c-a420a39be632,Сегодня будет ровно 6 месяцев с этого обещания...
3,31ea05ba-2c2b-4b84-aba7-f3cf6841b204,⚡️\nІзраїль вперше у світі збив балістичну рак...
4,a79e13ec-6d9a-40b5-b54c-7f4f743a7525,Склав невелику навчально-методичну таблицю на ...

,id,straw_man,appeal_to_fear,fud,bandwagon,whataboutism,loaded_language,glittering_generalities,euphoria,cherry_picking,cliche,Usage
0,521cd2e8-dd9f-42c4-98ba-c0c8890ff1ba,0,0,1,0,0,1,0,0,0,0,Public
1,9b2a61e4-d14e-4ff7-b304-e73d720319bf,0,0,0,0,0,1,0,0,0,0,Public
2,f0f1c236-80a8-4d25-b30c-a420a39be632,0,0,0,0,0,1,0,0,0,0,Public
3,31ea05ba-2c2b-4b84-aba7-f3cf6841b204,0,0,0,0,0,0,0,0,0,0,Public
4,a79e13ec-6d9a-40b5-b54c-7f4f743a7525,0,0,0,0,0,1,0,0,0,0,Public

,id,trigger_words,Usage
0,521cd2e8-dd9f-42c4-98ba-c0c8890ff1ba,"[(0, 12), (27, 46), (48, 71), (131, 162), (164...",Public
1,9b2a61e4-d14e-4ff7-b304-e73d720319bf,"[(374, 425)]",Public
2,f0f1c236-80a8-4d25-b30c-a420a39be632,"[(0, 127)]",Public
3,31ea05ba-2c2b-4b84-aba7-f3cf6841b204,NaN,Public
4,a79e13ec-6d9a-40b5-b54c-7f4f743a7525,"[(87, 103), (127, 136), (170, 189), (204, 255)...",Public

In [32]:
solution_classif['techniques'] = solution_classif.apply(lambda row: [col for col in solution_classif.columns if col != 'id' and col != 'Usage' and row[col] != 0], axis=1)

In [33]:
test = test.merge(solution_classif[['id', 'techniques']], on='id', how='left')
display(test.head())

,id,content,techniques
0,521cd2e8-dd9f-42c4-98ba-c0c8890ff1ba,"Они просрали нашу технику, положили кучу людей...","[fud, loaded_language]"
1,9b2a61e4-d14e-4ff7-b304-e73d720319bf,❗️\nКитай предлагает отдать оккупированные тер...,[loaded_language]
2,f0f1c236-80a8-4d25-b30c-a420a39be632,Сегодня будет ровно 6 месяцев с этого обещания...,[loaded_language]
3,31ea05ba-2c2b-4b84-aba7-f3cf6841b204,⚡️\nІзраїль вперше у світі збив балістичну рак...,[]
4,a79e13ec-6d9a-40b5-b54c-7f4f743a7525,Склав невелику навчально-методичну таблицю на ...,[loaded_language]

In [34]:
test = test.merge(solution_span[['id', 'trigger_words']], on='id', how='left')
display(test.head())

,id,content,techniques,trigger_words
0,521cd2e8-dd9f-42c4-98ba-c0c8890ff1ba,"Они просрали нашу технику, положили кучу людей...","[fud, loaded_language]","[(0, 12), (27, 46), (48, 71), (131, 162), (164..."
1,9b2a61e4-d14e-4ff7-b304-e73d720319bf,❗️\nКитай предлагает отдать оккупированные тер...,[loaded_language],"[(374, 425)]"
2,f0f1c236-80a8-4d25-b30c-a420a39be632,Сегодня будет ровно 6 месяцев с этого обещания...,[loaded_language],"[(0, 127)]"
3,31ea05ba-2c2b-4b84-aba7-f3cf6841b204,⚡️\nІзраїль вперше у світі збив балістичну рак...,[],NaN
4,a79e13ec-6d9a-40b5-b54c-7f4f743a7525,Склав невелику навчально-методичну таблицю на ...,[loaded_language],"[(87, 103), (127, 136), (170, 189), (204, 255)..."

In [36]:
test.to_csv('../data/test.csv', index=False)